language: php

php:
 - 7.0
 - 7.1
env:
  matrix:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

before_script:
 - composer install --no-interaction $COMPOSER_FLAGS

script:
 - phpunit

after_script:
 - php vendor/bin/coveralls -v
